const { sql } = require("../db");

const ProofModel = {
    /**
     * create - Record a new balance proof
     */
    async create({ userId, amount, currency, expiresAt }) {
        try {
            const proofs = await sql`
                INSERT INTO balance_proofs (user_id, amount, currency, expires_at)
                VALUES (${userId}, ${amount}, ${currency}, ${expiresAt})
                RETURNING *
            `;
            return proofs[0];
        } catch (error) {
            console.error("Error in ProofModel.create:", error);
            throw error;
        }
    },

    /**
     * findById - Find a proof by its UUID
     */
    async findById(id) {
        try {
            const proofs = await sql`
                SELECT * FROM balance_proofs WHERE id = ${id}
            `;
            return proofs[0];
        } catch (error) {
            console.error("Error in ProofModel.findById:", error);
            throw error;
        }
    },

    /**
     * listForUser - Get proofs generated by a user
     */
    async listForUser(userId) {
        try {
            return await sql`
                SELECT * FROM balance_proofs 
                WHERE user_id = ${userId} 
                ORDER BY created_at DESC
            `;
        } catch (error) {
            console.error("Error in ProofModel.listForUser:", error);
            throw error;
        }
    }
};

module.exports = ProofModel;
